name: codas-hep

channels:
- pytorch
- conda-forge

dependencies:
- cython
- elasticsearch
- graphviz
- h5py
- ipykernel
- ipywidgets
- jsanimation
- jupyter
- jupyterlab
- keras
- librosa
- matplotlib
- metakernel
- nb_conda_kernels
- numpy
- opencv
- pandas
- pillow
- pip
- pytables
- python=3.7
- pytorch
- qtpy
- rise
- root
- scipy
- seaborn
- scikit-learn
- tensorflow
- torchvision
- tqdm
- uproot
- pip:
  - gym
  - torchtext
  - torchviz
